#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     asf,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    jack1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    jack2,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Ramp code 3565
Alex McKinley
0.01: 10-01-14: basic code, no logic for grabbing tube yet because of hardware issues /
0.10: 10-23-14: added up and down servo and debugged them /
0.11: 11-4-14:   /  Lilia Heinold, William Engdahl, Brandon Wang
1.0 11-6-14:  Finish EVERYTHING! All Programmers
1.01 11-7-14: Add waitforstart menu and start fixing turns / Brandon Wang
1.10 11-13-14: Fix turns / Lilia Heinold,
1.2 11-14-14: Start dialing auto with new robot Akash, Will, Brandon
1.3 11-25-14: Code cleanup day: commenting, and refactoring - All Programmers
*/
#include "Standard_Drive.c";
#include "JoystickDriver.c";
#include "nxtIO.c";

bool inputWaitForStart();
int inputWaitSecs();

void servoUp()
{
	servo[jack1] = 225;
	servo[jack2] = 0;
}
void servoDown()
{
	servo[jack1] = 0;
	servo[jack2] = 225;
}


void raiseLift()
{
	ClearTimer(T1);
	while(abs(nMotorEncoder[elevator]) < 8400 && time1[T1] <2500)
	{
		motor[elevator] = 100;
		print(nMotorEncoder[elevator],4);
		PlaySound(soundBlip);
	}
	motor[elevator] = 0;
}

void lowerLift()
{
	ClearTimer(T1);
	while(abs(nMotorEncoder[elevator]) > 00 && time1[T1] <2500)
	{
		motor[elevator] = -100;
		print(nMotorEncoder[elevator],4);
		PlaySound(soundBlip);
	}
	motor[elevator] = 0;
}

void dump()
{
	servo[bucket] = 0;
}

void dumpUp()
{
	servo[bucket] = 225;

}
void initializeRobot()
{
	servo[bucket] = 225;
	servo[jack1] = 225;
	servo[jack2] = 0;

}

/*
Premovement robot stuff
-Wait for Start
-Wait time
-Initalize Robot
*/
void preMovement()
{
	//check for wait for start
	bool i = inputWaitForStart();
	wait1Msec(500);

	//Input wait seconds from display
	int waitSecs = inputWaitSecs();

	//Wait for start
	if(i)
	{
		waitForStart();
	}

	//Wait time
	wait1Msec(waitSecs*1000);	//Wait based on the selected value

	initializeRobot();
}

/**
Drive forward to right in front of the first 60 cm tube
**/
void moveToFirstTube()
{
	//drive to tube
	driveInches(60,33,27);
	wait1Msec(100);
	driveInches(24,50,50);
	wait10Msec(100);
	driveInches(4,22,22);
}

/*
Attach to the 60 cm rolling goal and dump the autonomous balls
*/
void attachAndDump()
{
	stopMotors();
	wait1Msec(500);
	servoDown();
	wait1Msec(500);
	driveInches(-5);
	raiseLift();
	wait1Msec(500);
	dump();
	wait1Msec(800);
	dumpUp();
	wait1Msec(500);
}

/**
Turn and drive towards the parking zone
**/
void moveToParkingZone()
{
	//Turn to angle back of robot towards parking zone
	nMotorEncoder[left] = 0;
	nMotorEncoder[right] = 0;
	while(abs(nMotorEncoder[left]) < inchesToEncoder(4.2))
	{
		motor[left]= 50;
		motor[right] = -50;
		print(nMotorEncoder[left], 4);
	}


	stopMotors();
	//drive backwards to parking zone
	driveInches(-100,50,50);

}

/**
Release the goal in the parking zone
**/
void parkGoal()
{
	//~180 turn so that rolling goal faces parking zone
	turn(LEFT,250,100);
	//drive forward, pushing goal into parking zone
	driveInches(10,50,50);
	//release rolling goal
	servoUp();
}

/*
Back away from the parking zone and get ready for the teleop phase
*/
void postParkGoal()
{
	driveInches(-8,50,50);
	turn(RIGHT,8,100);
	driveInches(-30,100,100);
	turn(RIGHT, 12,100);
	lowerLift();
	turn(LEFT,100,100);
}

task main()
{
	preMovement();
	moveToFirstTube();
	attachAndDump();
	moveToParkingZone();
	parkGoal();
	postParkGoal();
}

bool inputWaitForStart() {
	bool select = true;
	eraseDisplay();
	while(nNxtButtonPressed != 3) {
		if(nNxtButtonPressed == 1) { //Right arrow
			select = !select;
			PlaySound(soundBlip);
			eraseDisplay();
			wait1Msec(500);
		}
		else if(nNxtButtonPressed == 2) {
			select = !select;
			PlaySound(soundBlip);
			eraseDisplay();
			wait1Msec(500);
		}
		if(select)
			print(a, 2);
		else
			print(b, 2);
	}
	PlaySound(soundBlip);
	return select;
}

int inputWaitSecs() {
	int waitSecs = 0;
	eraseDisplay();
	print(waitSecs);
	while(nNxtButtonPressed != 3) {
		if(nNxtButtonPressed == 1) { //Right arrow
			waitSecs++;
			PlaySound(soundBlip);
			eraseDisplay();
			print(waitSecs);
			wait1Msec(500);
		}
		else if(nNxtButtonPressed == 2) {
			if(waitSecs > 0)
			{
				waitSecs--;
			}
			PlaySound(soundBlip);
			eraseDisplay();
			print(waitSecs);
			wait1Msec(500);
		}
	}
	PlaySound(soundBlip);
	return waitSecs;
}
