#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     ultra,          sensorSONAR)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    jack,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*IR Floor Code (7876)
Lilia Heinold, Alex McKinley
Version info in GitHub tags/releases.
*/

#include "Standard_Drive.c";
#include "JoystickDriver.c";
bool inputWaitForStart();
int inputWaitSecs();

/*
Start splitting center goal
Drive forward 35in
Check IR
	If IR is present - Position 1
	If Not
		Drive backward
		Turn Left 45
		Drive forward 35
		Turn Right 90
		Check IR
			If IR is present - Position 2
			If Not (Position 3)
				Turn right 45
				Forward 36 in
*/
//WORKING 3:20 pm 11/21 - 7876
task main()
{
	eraseDisplay();
	bool i = inputWaitForStart(); // Check for wait for start
	wait1Msec(500);

	// TODO: Shouldn't this NOT be asked if the user has decided not to wait for start?
	int waitSecs = inputWaitSecs(); // Input wait seconds from display

	if(i)
	{
		waitForStart();
	}
	wait1Msec(waitSecs*1000); // Wait based on the selected value

	driveInches(35,50,50); // Drive forward 35 inches
	print(SensorValue[ir]); // Display the value of the IR sensor
	wait1Msec(500);
	if(SensorValue[ir] >= 4 && SensorValue[ir] <= 6){ // If the IR beacon is present, drive to position 1
		PlaySound(soundBeepBeep);
		turn(RIGHT,90);
		driveInches(12,50,50);
		turn(LEFT,90);
		driveInches(48,50,50);
	}

/* THIS COPY OF THE COMMENT AT THE TOP IS TO AVOID SCROLLING
Start splitting center goal
Drive forward 35in
Check IR
	If IR is present - Position 1
	If Not
		Drive backward
		Turn Left 45
		Drive forward 35
		Turn Right 90
		Check IR
			If IR is present - Position 2
			If Not (Position 3)
				Turn right 45
				Forward 36 in
*/
	else{ // If we can't find an IR beacon...
		driveInches(-20,50,50);
		turn(LEFT,45);
		driveInches(35);
		turn(RIGHT,90);
		print(SensorValue[ir]);
		wait1Msec(500);
		if(SensorValue[ir] >= 5 && SensorValue[ir] <= 5){
			PlaySound(soundBeepBeep);
			driveInches(-6,50,50);
			turn(RIGHT,45);
			driveInches(15,50,50);
			turn(LEFT,40);
			driveInches(48,100,100);
		}
		else{
			turn(RIGHT,35);
			driveInches(36,100,100);
		}
	}


}

bool inputWaitForStart() { // Lets user specify whether he or she would like to wait for start
	bool select = true;
	eraseDisplay();
	while(nNxtButtonPressed != 3) { // Keep going until someone presses the big orange button
		// Toggle the select variable when the arrow buttons are pressed
		if(nNxtButtonPressed == 1) {
			select = !select;
			PlaySound(soundBlip);
			eraseDisplay();
			wait1Msec(500);
		}
		else if(nNxtButtonPressed == 2) {
			select = !select;
			PlaySound(soundBlip);
			eraseDisplay();
			wait1Msec(500);
		}
		// Print the state of the select variable
		// TODO: What are "a" and "b?" Should they be strings?
		if(select)
			print(a, 2);
		else
			print(b, 2);
	}
	PlaySound(soundBlip);
	// Return the value of select when the orange button is pressed.
	return select;
}

int inputWaitSecs() { // Lets user select the number of seconds to wait
	int waitSecs = 0;
	eraseDisplay();
	print(waitSecs);
	while(nNxtButtonPressed != 3) { // Wait until user presses the orange button
		if(nNxtButtonPressed == 1) { // Right arrow increases the number of wait seconds
			waitSecs++;
			PlaySound(soundBlip);
			eraseDisplay();
			print(waitSecs);
			wait1Msec(500);
		}
		else if(nNxtButtonPressed == 2) { // Left arrow decreases the number of wait seconds
			if(waitSecs > 0)
			{
				waitSecs--;
			}
			PlaySound(soundBlip);
			eraseDisplay();
			print(waitSecs);
			wait1Msec(500);
		}
	}
	PlaySound(soundBlip);
	return waitSecs;
}
