#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     ultra,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Auto_Floor
  Lilia Heinold, Will Engdahl, Andrew Sun.com
  11/6/14 .001: Wrote basic code,
*/
#include "lib/Standard_Drive.c";
#include "lib/nxtIO.c";

task main()
{
	//Drive to centerpiece
	driveInches(48,100,100);
	turn(LEFT,45);
	driveInches(2,100,100);

	if(sensorValue[ultra] < 16 && sensorValue[ultra] != 255){ //If it is in position 2
		driveInches(-3);
		turn(LEFT,45);
		//driveInches(??,100,100);
	}

	else if(sensorValue[ultra] > 17 && sensorValue[ultra] != 255){ //If it is in position 1 or 3
		driveInches(-3);
		turn(LEFT,45);
		driveInches(10,100,100);
	}

	//For position 1 or 3
	driveInches(5,100,100);
	turn(LEFT,90);
	driveInches(12,100,100);
}
