#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     asf,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    jack1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    jack2,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*IR Floor Code (3565)
Lilia Heinold, Alex McKinley
Version info in GitHub tags/releases.
*/

#include "Standard_Drive.c";
#include "JoystickDriver.c";

/*
Start splitting center goal
Drive forward 30in
Check IR
	If IR is present - Position 1
	If Not
		Turn Right 45
		Drive forward 12sqrt(2)
		Turn Left 90
		Check IR
			If IR is present - Position 2
			If Not (Position 3)
				Turn right 45
				Forward 36 in
				Left 90
				Forward 48
*/

task main()
{
	driveInches(30,50,50);
	print(SensorValue[ir]);
	wait1Msec(500);
	if(SensorValue[ir] >= 4 && SensorValue[ir] <= 6){
		turn(RIGHT,90);
		driveInches(12,50,50);
		turn(LEFT,90);
		driveInches(48,50,50);
	}
	else{
		driveInches(-15,50,50);
		turn(LEFT,45);
		driveInches(25);
		turn(RIGHT,100);
		print(SensorValue[ir]);
		wait1Msec(500);
		if(SensorValue[ir] >= 4 && SensorValue[ir] <= 6){
			driveInches(-6,50,50);
			turn(RIGHT,45);
			driveInches(15,50,50);
			turn(LEFT,40);
			driveInches(48,50,50);
		}
		else{
			turn(RIGHT,45);
			driveInches(36,50,50);
		}
	}


}
