#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultra,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    jack,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DOUBLE_JOYSTICK true
#define SINGLE_JOYSTICK false
/*Brandon Wang, Lilia Heinold
Teleop 3565 (Name pending)
1.0 10/3 First Teleop Test (robot base)
1.1 11/7 Robot base with rolling goal servos
*/
#include "JoystickDriver.c"
#include "Standard_Drive.c";
//#include "nxtIO.h";

void initializeRobot()
{
	motor[left] = 0;
	motor[right] = 0;
	nMotorEncoder[left] = 0;
}

/*
* @return angle relative to the front of the robot in radians
*/
float getAngle()
{
	getJoystickSettings(joystick);
	long y = joystick.joy1_y1;
	long x = joystick.joy1_x1;

	float angle = atan(y/x);
	return angle - PI/2;
}


float turnRadians(float rad)
{
	return ROBOT_RADIUS * rad * 2;
}

int getRightPower() //right motor power
{
	getJoystickSettings(joystick);

	long y2 = joystick.joy1_y2;
	long x2 = joystick.joy1_x2;
	long y = joystick.joy1_y1;
	long x = joystick.joy1_x1;
	float value;
	if(sqrt(x*x+y*y) > 10)
	{
		value =	(((y * y * y - x * x * x) * 100) >> 21);
	}
	else if (sqrt(x2*x2+y2*y2) > 10)
	{
		value = (((y2 * y2 * y2 - x2 * x2 * x2) * 100) >> 21) / 2;
	}
	else
	{
		value = 0;
	}

	return value;
}

int getLeftPower() //left motor power
{
	getJoystickSettings(joystick);

	long y2 = joystick.joy1_y2;
	long x2 = joystick.joy1_x2;
	long y = joystick.joy1_y1;
	long x = joystick.joy1_x1;
	float value;
	if(sqrt(x*x+y*y) > 10)
	{
		value =	(((y * y * y + x * x * x) * 100) >> 21);
	}
	else if (sqrt(x2*x2+y2*y2) > 10)
	{
		value = (((y2 * y2 * y2 + x2 * x2 * x2) * 100) >> 21) / 2;
	}
	else
	{
		value = 0;
	}
	return value;
}


task main()
{
	initializeRobot();
	bool joyStickMode = SINGLE_JOYSTICK;
	int angle = 0;

	while (true)
	{
		getJoystickSettings(joystick);

		long y2 = joystick.joy1_y2;
		long y = joystick.joy1_y1;

		if(abs(angle-getAngle()) > 5*180/PI)
		{
			angle = getAngle();
			nMotorEncoder[left] = 0;
		}
		if(joyStickMode == DOUBLE_JOYSTICK)
		{
			//two joysticks
			if(sqrt(y2*y2+y*y) > 10)
			{
				motor[left] = y;
				motor[right] = y2;
			}
			else
			{
				motor[left] = 0;
				motor[right] = 0;
			}
		}

		if(joyStickMode == SINGLE_JOYSTICK) //One joystick
		{
			//if encoder reading is less than the encoders needed to turn, keep turning
			if(abs(nMotorEncoder[motorD]) < inchesToEncoder(turnRadians(angle)))
			{
				//if statement for the shortest route
				if(angle > 3*PI/2)//turn left
				{
					motor[motorD] = -getLeftPower();
					motor[motorE] = getRightPower();
				}
				else //turn right
				{
					motor[motorD] = getLeftPower();
					motor[motorE] = -getRightPower();
				}
			}
			else//robot has achieved the turn, start going forward
			{
				motor[motorD] = getLeftPower();
				motor[motorE] = getRightPower();
			}
		}
		//one button at a time
		//First Controller Buttons
		if(joy1Btn(9) == 1 || joy1Btn(10) == 1)
		{ //Switch between dual and single joystick,,l
			PlayTone(1000,5);
			joyStickMode = !joyStickMode;
			wait1Msec(1000);
		}

		if (joy2Btn(4) == 1 && joy2Btn(2) == 0)
		{
			servo[jack] = ServoValue[jack] + 5;
		}
		else if(joy2Btn(2) == 1 && joy2Btn(4) == 0)
		{
			servo[jack] = ServoValue[jack] - 5;
		}

		//if (joy2Btn(7) == 1 && joy2Btn(8) == 0){
		//	motor[elevator] = 100;
		//}
		//else if (joy2Btn(8) == 0 && joy2Btn(7) == 0) {
		//	motor[elevator] = -100;
		//}

		if(joystick.joy2_TopHat == 0 && joystick.joy2_TopHat != 4)
		{
			servo[bucket] = ServoValue[bucket] + 4;
		}
		else if(joystick.joy2_TopHat == 4 && joystick.joy2_TopHat != 0)
		{
			servo[bucket] = ServoValue[bucket] - 4;
		}

	}
}
