#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultra,          sensorNone)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     spinner,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    grab,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Brandon Wang, Lilia Heinold, Will Engdahl
Teleop 7876 (Name pending)
1.0 10/3 First Teleop Test (robot base)
1.1 11/7 Robot base with rolling goal servos
1.2 1/9/14 Added virtual gears, fixed problem with lift raising on "Teleop Ready" state
*/
#include "JoystickDriver.c"
#include "Standard_Drive.c";
#include "nxtIO.c";

void initializeRobot()
{
	motor[left] = 0;
	motor[right] = 0;
	motor[lift1] = 0;
	motor[lift2] = 0;
	servo[bucket] = 0;
	servo[grab] = 0;
	nMotorEncoder[left] = 0;
	//TODO: figure out servo initialization values
}

task main()
{
	waitForStart();
	initializeRobot();
	float gearFactor = 1;
	 // The joystick tophat is set to 0 when the teleop is set to "ready"
	while (true)
	{
		getJoystickSettings(joystick);
		//two joysticks
		long y2 = joystick.joy1_y2;
		long y = joystick.joy1_y1;

			//two joysticks
		if(sqrt(y2*y2+y*y) > 10)
		{
			motor[left] = -gearFactor*y;
			motor[right] = -gearFactor*y2;
		}
		else
		{
			motor[left] = 0;
			motor[right] = 0;
		}
		//virtual gears on driver controller
		if(joy1Btn(1) == 1)
		{
			PlaySound(soundBlip);
			gearFactor = 0.25;
		}else if(joy1Btn(2) == 1)
		{
			PlaySound(soundBlip);
			gearFactor = 0.5;
		}else if(joy1Btn(3) == 1)
		{
			PlaySound(soundBlip);
			gearFactor = 0.75;
		}else if(joy1Btn(4) == 1)
		{
			PlaySound(soundBlip);
			gearFactor = 1;
		}

		if (joy2Btn(4) == 1 && joy2Btn(2) == 0)
		{
			servo[grab] = ServoValue[grab] + 5;
		}
		else if(joy2Btn(2) == 1 && joy2Btn(4) == 0)
		{
			servo[grab] = ServoValue[grab] - 5;
		}

		int joy2y1 = joystick.joy2_y1;
		if(abs(joy2y1) < 10)
		{
			joy2y1 = 0;
		}

		motor[lift1] = joy2y1;

		int joy2y2 = -joystick.joy2_y2;
		if(abs(joy2y2) < 10)
		{
			joy2y2 = 0;
		}

		motor[lift2] = joy2y2;

		if(joystick.joy2_TopHat == 0 && joystick.joy2_TopHat != 4)
		{
			servo[bucket] = 0;
		}
		else if(joystick.joy2_TopHat == 4 && joystick.joy2_TopHat != 0)
		{
			servo[bucket] = 255;
		}


		//spinner
		if(joy2btn(7) == 1 && joy2Btn(8) == 0)
		{
			motor[spinner] = 100;
		}
		else if(joy2btn(8) == 1 && joy2Btn(7) == 0)
		{
				motor[spinner] = -100;
		}else if(joy2btn(5) == 1 && joy2Btn(6) == 0)
		{
				motor[spinner] = 20;
		}
		else if(joy2btn(6) == 1 && joy2Btn(5) == 0)
		{
				motor[spinner] = -20;
		}

		print(servovalue[bucket],3);
	}
}
