#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     asf,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    jack1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    jack2,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Ramp code 3565
Alex McKinley
0.01: 10-01-14: basic code, no logic for grabbing tube yet because of hardware issues /
0.10: 10-23-14: added up and down servo and debugged them /
0.11: 11-4-14:   /  Lilia Heinold, William Engdahl, Brandon Wang
1.0 11-6-14:  Finish EVERYTHING! All Programmers
1.01 11-7-14: Add waitforstart menu and start fixing turns / Brandon Wang
1.10 11-13-14: Fix turns / Lilia Heinold,
1.2 11-14-14: Start dialing auto with new robot Akash, Will, Brandon
*/
#include "Standard_Drive.c";
#include "JoystickDriver.c";
#include "nxtIO.c";

bool inputWaitForStart();

void servoUp()
{
	servo[jack1] = 225;
	servo[jack2] = 0;
}
void servoDown()
{
	servo[jack1] = 0;
	servo[jack2] = 225;
}


void raiseLift()
{
	ClearTimer(T1);
	while(abs(nMotorEncoder[elevator]) < 8400 && time1[T1] <2500)
	{
		motor[elevator] = 100;
		print(nMotorEncoder[elevator],4);
		PlaySound(soundBlip);
	}
	motor[elevator] = 0;
}
void dump()
{
	servo[bucket] = 0;
}

void dumpUp()
{
	servo[bucket] = 225;

}
void initializeRobot()
{
	servo[bucket] = 225;
	servo[jack1] = 225;
	servo[jack2] = 0;

}

task main()
{

	eraseDisplay();
	bool i = inputWaitForStart();//check for wait for start
	wait1Msec(500);




	if(i)
	{
		waitForStart();
	}



	initializeRobot();

	/*
	nMotorEncoder[left] = 0;
	while(abs(nMotorEncoder[left]) < inchesToEncoder(32))
	{
		motor[right]=100;
		motor[left] = 0;
		PlaySound(soundBeepBeep);
	}

	stopMotors();
	return;
	*/

	driveInches(84,100,60); //drive to tube
	stopMotors();
	wait1Msec(500);
	servoDown();
	wait1Msec(500);
	driveInches(-5);
	raiseLift();
	wait1Msec(500);
	dump();
	wait1Msec(800);
	dumpUp();
	wait1Msec(500);
	// turn around and drive to ramp
	nMotorEncoder[left] = 0;
	//start of floor code
		//turn around and drive to ramp
	nMotorEncoder[right] = 0;
	//start of floor code
	//go flat against wall


	while(abs(nMotorEncoder[left]) < inchesToEncoder(4.1))
	{
		motor[left]= 50;
		motor[right] = -50;

		print(nMotorEncoder[left], 4);
	}

	//turn towards floor parking zone
	stopMotors();

	//drive to parking zone
	driveInches(-110,50,50);
	turn(LEFT,220,100);
	//release thingy
	servoUp();

	turn(RIGHT,8,100);
	driveInches(-30,100,100);
	turn(RIGHT, 12,100);
	return;
	//start of ramp code
	while(abs(nMotorEncoder[left]) < inchesToEncoder(64))
	{
		motor[right]=100;
		motor[left] = 0;
	}

	stopMotors();

	//driveInches(4);
	//driveInches(40,50,0);
	turn(LEFT, 40);
	driveInches(257,100,100);
	turn(RIGHT, 30);
	wait1Msec(5000);
	PlaySound(soundFastUpwardTones);
	driveInches(30, 50, 50);
	wait1Msec(500);
	turn(LEFT, 30);
	wait1Msec(500);
	driveInches(30, 50, 50);
	servoUp();
	//drive back off of ramp
	driveInches(-90);
}

bool inputWaitForStart() {
	bool select = true;
	eraseDisplay();
	while(nNxtButtonPressed != 3) {
		if(nNxtButtonPressed == 1) { //Right arrow
			select = !select;
			PlaySound(soundBlip);
			eraseDisplay();
			wait1Msec(500);
		}
		else if(nNxtButtonPressed == 2) {
			select = !select;
			PlaySound(soundBlip);
			eraseDisplay();
			wait1Msec(500);
		}
		if(select)
			print(a, 2);
		else
			print(b, 2);
	}
	PlaySound(soundBlip);
	return select;
}
