#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultra,          sensorNone)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     spinner,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    grab,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Standard_Drive.c"
//#include "Standard_Drive.h"
#include "nxtIO.c"
#include "JoystickDriver.c"
//#include "nxtIO.h"

void initialize();
void initialize() {
	servo[grab] = 0;
}

void grabDown();
void grabDown() {
	servo[grab] = 255;
}
void grabUp();
void grabUp() {
	servo[grab] = 0;
}

task main()
{
	PlaySound(soundBeepBeep);
	initialize();
	waitForStart();
	driveInches(107);
	grabDown();
	driveInches(-107);


}
